### ISSUE TITLE
Fuzzy Conversions (FUZZYCON)

### ISSUE THREAD

**Issue by aryamasinha** [aryamasinha/Hacktoberfest_2020#35]

**Comment by Satvik-B** [comment]
@aryamasinha will do this, please assign this to me

**Comment by khushboogupta13** [comment]
I have done this!

**Comment by kokilgupta** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/63225401/95199022-c9462280-07f9-11eb-9f87-19a93b4501f9.png)
