### ISSUE TITLE
Socializing Game around Pizza (BIGPIZA)

### ISSUE THREAD

**Issue by aryamasinha** [aryamasinha/Hacktoberfest_2020#37]

**Comment by ojas032** [comment]
I would like to work on it. Please assign it to me..

**Comment by ojas032** [comment]
@aryamasinha I would like to work on it. Please assign it to me..

**Comment by AniruddhaChattopadhyay** [comment]
@aryamasinha Can I please take this up since there is no one this is assigned to currently?
